//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormOturumAcmaİslemi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WinFormOturumAcmaİslemiEntitiesConnectionDb : DbContext
    {
        public WinFormOturumAcmaİslemiEntitiesConnectionDb()
    : base("name=WinFormOturumAcmaİslemiEntitiesConnectionDb")
        {
        }


        
    
        public virtual DbSet<Kullanici_Giris_Tablosu> Kullanici_Giris_Tablosu { get; set; }
    }
}
